# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/msg/basic_msgs/header.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from modules.msg.basic_msgs import error_code_pb2 as modules_dot_msg_dot_basic__msgs_dot_error__code__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n#modules/msg/basic_msgs/header.proto\x12\rbyd.msg.basic\x1a\'modules/msg/basic_msgs/error_code.proto\"\x88\x02\n\x06Header\x12\x19\n\x11publish_timestamp\x18\x01 \x01(\x01\x12\x1d\n\x15measurement_timestamp\x18\x02 \x01(\x01\x12\x13\n\x0bmodule_name\x18\x03 \x01(\t\x12\x14\n\x0csequence_num\x18\x04 \x01(\r\x12\x17\n\x0flidar_timestamp\x18\x05 \x01(\x01\x12\x18\n\x10\x63\x61mera_timestamp\x18\x06 \x01(\x01\x12\x17\n\x0fradar_timestamp\x18\x07 \x01(\x01\x12\x12\n\x07version\x18\x08 \x01(\r:\x01\x31\x12\'\n\x06status\x18\t \x01(\x0b\x32\x17.byd.msg.basic.StatusPb\x12\x10\n\x08\x66rame_id\x18\n \x01(\t')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'modules.msg.basic_msgs.header_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_HEADER']._serialized_start=96
  _globals['_HEADER']._serialized_end=360
# @@protoc_insertion_point(module_scope)
